---
sot:
  api_endpoint: "http://127.0.0.1:8000"

files:
  prefixe:
    repo: network_design
    filename: defaults/defaults.yaml
  sites:
    repo: network_design
    filename: defaults/defaults.yaml

onboarding:
  defaults:
    interface:
      - Loopback0
      - Loopback100
  tags:
    interfaces:
      ospf: "^ ip ospf"

