---
sot:
  api_endpoint: "http://127.0.0.1:8000"

onboarding:
  defaults:
    interface:
      - Loopback100
      - Loopback0
    devicetype: vios_router
    role: pod_router
    manufacturer: cisco
    platform: cisco_ios
    site: default
    status: active
  tags:
    interfaces:
      ospf: "^ ip ospf"

