---
sot:
  api_endpoint: "http://127.0.0.1:8000"

files:
  prefixe:
    repo: sot_data
    filename: defaults/prefixe.yaml
  defaults:
    repo: sot_data
    filename: defaults/defaults.yaml
  sites:
    repo: sot_data
    filename: defaults/sites.yaml

logins:
  lab:
    username: lab
    password: lab

onboarding:
  defaults:
    # the default primary interface we use to get the primary address
    interface:
      - Loopback0
      - Loopback100
  tags:
    interfaces:
      # to set a tag configure tag name and regular expression here
      ospf: "^ ip ospf"
      dhcp: "^ ip address dhcp"

